apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaegul.fullname" . }}
  labels:
    {{- include "gaegul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "gaegul.selectorLabels" . | nindent 4 }}
